name: Docker Build Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 8
        format: 'YYYY-MM-DD HH:mm:ss'

    - name: Build the Docker image
      env:
        VITE_APP_TIMESTAMP: ${{ steps.time.outputs.time }}
        VITE_APP_GIT_SHA: ${{ github.sha }}
      run: docker build . --file Dockerfile --tag gzctf:test
