name: Build & Publish Image (amd64)

on:
  push:
    branches: [ "develop", "ci-test*" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: gztime
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          # List of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/gzctf/gzctf
            gztime/gzctf
          # List of tags as key-value pair attributes
          tags: |
            latest
            type=ref,event=branch
            type=semver,pattern={{raw}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      - name:  Build and push
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TIMESTAMP=${{ steps.time.outputs.time }}
            GIT_SHA=${{ github.sha }}
            GIT_NAME=${{ github.ref_name }}
          push: true

      - name: Prune old packages
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          token: ${{ secrets.PACKAGE_TOKEN }}
          container: "gzctf/gzctf"
          dry-run: false
          tag-regex: ^[0-9a-f]{6,40}
          keep-tags: |
            latest
            main
            develop
          keep-tags-regexes:
            ^v(.)*
          keep-last: 5
          untagged: true
