name: Build & Publish Image

on:
  push:
    branches: [ "develop" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8

      - name: Build and publish Docker Image to GitHub Packages Registry
        id: publish
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          buildArgs: |
            TIMESTAMP=${{ steps.time.outputs.time }}
            GIT_SHA=${{ github.sha }}
            GIT_NAME=${{ github.ref_name }}
          tag: |
            latest
            ${{ github.ref_name }}
            ${{ github.sha }}

      - name: Prune old packages
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          token: ${{ secrets.PACKAGE_TOKEN }}
          container: "gzctf/gzctf"
          dry-run: false
          tag-regex: ^[0-9a-f]{40}
          keep-tags: |
            latest
            main
            develop
          keep-tags-regexes:
            ^v(.)*
          keep-last: 5
          untagged: true

      - name: Print full Image URL
        run: echo ${{ steps.publish.outputs.imageURL }}:${{ github.sha }}
