name: Build & Publish Image

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD_HH:mm:ss'

      - name: Build and publish Docker Image to GitHub Packages Registry
        id: publish
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          buildArgs: |
            TIMESTAMP=${{ steps.time.outputs.time }}
            GIT_SHA=${{ github.sha }}
            GIT_NAME=${{ github.ref_name }}
          tag: |
            latest
            ${{ github.ref_name }}
            ${{ github.sha }}

      - name: Delete Old Package
        uses: actions/delete-package-versions@v2.0.1
        with:
            package-name: 'gzctf/gzctf'
            ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'
            min-versions-to-keep: 5
      
      - name: Print Full Image URL
        run: echo ${{ steps.publish.outputs.imageURL }}:${{ github.sha }}
